export const fallbackDashboard = {
  farmer: {
    _id: "farmer-rajesh",
    name: "Rajesh Kumar",
    phoneNo: "9000012345",
    aadharNo: "1234-5678-9012",
    landAreaHectare: 1.5,
    location: {
      district: "Lucknow",
      state: "Uttar Pradesh",
    },
    caste: "OBC",
    crops: ["Wheat", "Rice"],
    annualIncome: 140000,
    phoneType: "smartphone",
    smartphoneProficiency: "high",
    phoneUserCategory: "SMARTPHONE_USER",
  },
  stats: {
    eligibleSchemes: 4,
    activeApplications: 2,
  },
  prioritizedSchemes: [
    {
      _id: "scheme-pmkisan",
      title: "PM-Kisan Samman Nidhi",
      category: "Central",
      summary: "Income support of Rs. 6,000 per year",
      benefit: "Rs. 6,000 per year",
      priorityWeight: 95,
      score: 98,
      requiredDocuments: ["Aadhaar Card", "Land Records", "Bank Passbook"],
      applyLinks: [{ label: "PM-Kisan Portal", url: "https://pmkisan.gov.in" }],
      cscGuidance:
        "Can be applied from nearest CSC center with biometric verification.",
      estimatedChargeInr: 40,
      deadline: "31 Mar 2026",
      reasons: ["Priority weight: 95"],
    },
    {
      _id: "scheme-kcc",
      title: "Kisan Credit Card (KCC)",
      category: "Financial",
      summary: "Low-interest crop loan up to Rs. 3 Lakh",
      benefit: "Loan up to Rs. 3 Lakh",
      priorityWeight: 90,
      score: 93,
      requiredDocuments: ["Aadhaar", "Voter ID", "Land Possession Certificate"],
      applyLinks: [{ label: "KCC Apply Link", url: "https://pmkisan.gov.in/Kcc/" }],
      cscGuidance: "CSC or cooperative bank branch can file the application.",
      estimatedChargeInr: 80,
      deadline: "15 Apr 2026",
      reasons: ["Crop profile aligned", "Priority weight: 90"],
    },
    {
      _id: "scheme-pmfbby",
      title: "PM Fasal Bima Yojana",
      category: "Insurance",
      summary: "Crop insurance for weather and yield risk",
      benefit: "Premium subsidy and loss compensation",
      priorityWeight: 82,
      score: 85,
      requiredDocuments: [
        "Aadhaar Card",
        "Land Record",
        "Sowing Certificate",
        "Bank Passbook",
      ],
      applyLinks: [{ label: "PMFBY Portal", url: "https://pmfby.gov.in" }],
      cscGuidance: "Submit at CSC or insurance-enabled agriculture office.",
      estimatedChargeInr: 50,
      deadline: "30 Apr 2026",
      reasons: ["Crop profile aligned", "Priority weight: 82"],
    },
    {
      _id: "scheme-psby",
      title: "PM Suraksha Bima Yojana",
      category: "Insurance",
      summary: "Accidental insurance cover of Rs. 2 Lakh",
      benefit: "Accidental insurance cover of Rs. 2 Lakh",
      priorityWeight: 70,
      score: 70,
      requiredDocuments: ["Aadhaar Card", "Bank Account", "Mobile Number"],
      applyLinks: [{ label: "Jan Suraksha Portal", url: "https://jansuraksha.gov.in" }],
      cscGuidance: "Enroll through bank CSP, branch, or CSC.",
      estimatedChargeInr: 20,
      deadline: "Open all year",
      reasons: ["Priority weight: 70"],
    },
  ],
  applications: [
    {
      _id: "app-1",
      farmer: "farmer-rajesh",
      scheme: {
        _id: "scheme-pmkisan",
        title: "PM-Kisan Samman Nidhi",
        category: "Central",
      },
      applicationNumber: "APP-4289-092",
      status: "approved",
      submittedAt: "2026-01-15T10:00:00.000Z",
      timeline: [
        { step: "Applied", status: "completed", dateLabel: "Jan 15" },
        { step: "Verification", status: "completed", dateLabel: "Jan 22" },
        { step: "Approval", status: "completed", dateLabel: "Jan 28" },
        { step: "Disbursement", status: "pending", dateLabel: "TBD" },
      ],
      receiptUrl: "https://example.org/receipt/app-4289-092.pdf",
    },
    {
      _id: "app-2",
      farmer: "farmer-rajesh",
      scheme: {
        _id: "scheme-kcc",
        title: "Kisan Credit Card (KCC)",
        category: "Financial",
      },
      applicationNumber: "APP-5130-119",
      status: "verification",
      submittedAt: "2026-02-03T10:00:00.000Z",
      timeline: [
        { step: "Applied", status: "completed", dateLabel: "Feb 3" },
        { step: "Aadhaar Verification", status: "in_progress", dateLabel: "Pending" },
        { step: "Bank Approval", status: "pending", dateLabel: "Pending" },
      ],
      receiptUrl: "",
    },
  ],
  callLogs: [
    {
      _id: "call-1",
      farmer: "farmer-rajesh",
      farmerName: "Rajesh Kumar",
      callType: "outbound",
      status: "completed",
      summary: "Farmer confirmed intent to apply.",
      nextAction: "Follow-up call in 5 days for application number.",
      applicationNumber: "",
      callAt: "2026-03-28T15:03:43.000Z",
    },
    {
      _id: "call-2",
      farmer: "farmer-rajesh",
      farmerName: "Rajesh Kumar",
      callType: "follow_up",
      status: "completed",
      summary: "Farmer confirmed intent to apply.",
      nextAction: "Ask if application was submitted via CSC.",
      applicationNumber: "",
      callAt: "2026-03-28T15:03:35.000Z",
    },
  ],
};
